### ISSUE TITLE
Create "API Token" setting and send it with requests

### ISSUE THREAD

**Issue by groovecoder** [codesy/chrome-extension#31]
Django Rest Framework - as it should - enforces CSRF protection when using [SessionAuthentication](http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication).

The browser extensions execute their form and AJAX requests from the bug domains. (e.g., github.com) So, the HTTP Referer - github.com - does not match the server-side domain - codesy.io, and the CSRF validation fails.

So, we need to change DRF to [TokenAuthentication](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication), which doesn't enforce CsrfMiddleware 'Referer' matching, and  is probably better anyway. To do so, we should:

* [ ] https://github.com/codesy/codesy/issues/72
* [ ] #25 After install, on the first run with the extension, open settings panel with an "API Token" input field for the API token
* [ ] Update the browser extension(s) code to send `Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b` with requests.

**Comment by jdungan** [comment]
Fix via #40
