### ISSUE TITLE
Use content script to adjust #install-step contents

### ISSUE THREAD

**Issue by groovecoder** [codesy/chrome-extension#43]
To change the home page for users who already have the browser extension, make the content script replace the contents of the `#install-step` element with:
```
<h2>Installed. <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></h2>
```

**Comment by jdungan** [comment]
Rather than replace, we should load two elements.  One with install instructions.  One with the html above set to hidden.  The content script would just flip the first to hidden and the turn off hiding on the second.  This would avoid putting specific html in the extension.
